apiVersion: v1
kind: Secret
metadata:
    name: dp-registry-postgres-secret
    namespace: data-infra
type: Opaque
stringData:
    postgres_password: ENC[AES256_GCM,data:G1mG1wZef6g=,iv:b2vCfQSsVxqqpElvltVWm25LyKB434EKNKW12PE8EkI=,tag:ssEWfnz0kLtbnFXhLfnIWA==,type:str]
sops:
    age:
        - recipient: age1t9hxk98xxze92rxjyq77q79gw7lf6jwa5pn83zqp037qq725z4lsxvqf8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dC83aTgvajI3bS96RnRr
            eUM5VUtmU1NDcjZjSkNSQUtoeERiZGpURWxzCnk0TWZHejFLWFg5b1V0Q0J3V1Bt
            anduTEdrWWppR1F3QyszbnNqcGh4VzAKLS0tIDViS3BFQU5BdkZlUVMvYmhtOTYw
            dTdRcW9qRFh3bUhUVzdObHRvT2lJWFUKnchG3893QlEhWHCVWwFSfywO9+3RB4zL
            yo9lE0JpG+/jBN21J31MGwLQyvSzgVVK1RlInm9s5vqYGa6Fpnj3kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T10:37:24Z"
    mac: ENC[AES256_GCM,data:Ft5/+CO1lo69A2wF+S3AvUBiEvk08uJjpgDPDxa8cx8PGKrruEF8TdMCkpYa53jmbyNbBR60zAIQDDq9vbgAI8/MNwrUqTm3R+bcymZD4aQa5h+aiPNKPIszjRzU9vLrsaCjbl+XT+fjIjhPs7sOmNi1vX+jnXBFR2yu3j6zLNU=,iv:rDreObT/Ej5PGKtCDRiWRE43sH4fjlEn6M+v0gaJwzk=,tag:MlbcPl5KRtZozv8LG9Wagg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
