apiVersion: v1
kind: ConfigMap
metadata:
  name: nessie-config
  namespace: data-infra
data:
  application.properties: |
    nessie.version.store.type=JDBC
    nessie.version.store.persist.jdbc.datasource=postgresql
    quarkus.datasource.postgresql.jdbc.url=jdbc:postgresql://dp-postgres:5432/catalog
    quarkus.datasource.postgresql.username=postgres
    nessie.catalog.default-warehouse=datalake
    nessie.catalog.warehouses.datalake.location=s3://datalake-bronze-zone/
    nessie.catalog.service.s3.default-options.endpoint=http://dp-minio-endpoint:9000/
    nessie.catalog.service.s3.default-options.region=us-east-1
    nessie.catalog.service.s3.default-options.path-style-access=true
    nessie.catalog.service.s3.default-options.access-key=urn:nessie-secret:quarkus:nessie.catalog.secrets.access-key
    nessie.catalog.secrets.access-key.name=${NESSIE_CATALOG_SECRETS_ACCESS_KEY_NAME}
    nessie.catalog.secrets.access-key.secret=${NESSIE_CATALOG_SECRETS_ACCESS_KEY_SECRET}
    nessie.server.authorization.enabled=false
