apiVersion: v1
kind: Secret
metadata:
    name: dp-registry-postgres-secret
    namespace: data-infra
type: Opaque
stringData:
    postgres_password: ENC[AES256_GCM,data:G1mG1wZef6g=,iv:b2vCfQSsVxqqpElvltVWm25LyKB434EKNKW12PE8EkI=,tag:ssEWfnz0kLtbnFXhLfnIWA==,type:str]
sops:
    age:
        - recipient: age1t9hxk98xxze92rxjyq77q79gw7lf6jwa5pn83zqp037qq725z4lsxvqf8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVDQrL1JKbUxVOGZONXZn
            czhERW1qblZmejBBNnNHeWljU1ZaeEk0WDNrCkUrYU9tZldVaDJIM0xCMWVxamhI
            dUxqdkxEUUZ3eHpvZXVibWVQWjBpaDgKLS0tIDUwcmlKeHhCUmFEdmh4SHA5eXZR
            VnhoaHg3Q2xUaXZaRWxLbW12UmMzK0kKg++RjL/6GGcfP+PK4MwFKnf8t3fU8Z8T
            Cg9LUBl0CKkfGInsCEDgMbGYXLxsQmhbOG/zTbo0U6jywf2FN6FV2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1da648as9sztwp6hkjlklqxzcynrxzqazywpw97x5rs7pmv7yup8sn08zqk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUXUxYkhqNllOZmhQVVYv
            aTZEU28zYjFqaVppSk1iUVpyOWIwemJpYVRvCkdIcTRQNnlYS2lONjFUb1pOUlcv
            MGp0VTVrWkEwVjBPbHpmVkxNS2gyMEkKLS0tICsxRmhENW1PTXE4Z2tIb3pzMk1m
            dUk5USs2alhsQTRJY0o1M21HZkljaEkKpasTeL40k1ee8QXjw0oFKKH4AQuEky8f
            K7VKTDgFDAblGZXbKCkH1WYfVmhDhhdnqUwUk2BweAJbUIboQsh+xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T10:37:24Z"
    mac: ENC[AES256_GCM,data:Ft5/+CO1lo69A2wF+S3AvUBiEvk08uJjpgDPDxa8cx8PGKrruEF8TdMCkpYa53jmbyNbBR60zAIQDDq9vbgAI8/MNwrUqTm3R+bcymZD4aQa5h+aiPNKPIszjRzU9vLrsaCjbl+XT+fjIjhPs7sOmNi1vX+jnXBFR2yu3j6zLNU=,iv:rDreObT/Ej5PGKtCDRiWRE43sH4fjlEn6M+v0gaJwzk=,tag:MlbcPl5KRtZozv8LG9Wagg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
