apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: data-infra-prod-postgres-secret
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: data-platform
  path: ./secrets/prod-postgres/overlays/debezium
  prune: true
  wait: true
  dependsOn:
  - name: namespaces
  decryption:
    provider: sops
    secretRef:
      name: sops-age
