apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nessie.labels" . | nindent 4 }}
data:
  application.properties: |
    {{- .Values.configMap.applicationProperties | nindent 4 }}
