apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nessie.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "nessie.selectorLabels" . | nindent 4 }}
  ports:
  - name: nessie-portal
    protocol: TCP
    port: {{ .Values.service.ports.portal }}
    targetPort: {{ .Values.service.ports.portal }}
  - name: nessie-api
    protocol: TCP
    port: {{ .Values.service.ports.api }}
    targetPort: {{ .Values.service.ports.api }}
