apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-secret
    namespace: data-infra
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:ZvyMlpKJPAi8dK1eW0Pfw7tUXQV1vYVWUvo0OcIDrE4+gRWm/bsf2Hl4wJQnmsuZxlAmFUcF5bMTeDfgPRLwboboQGQyJr5tzy+NTRJaUcb0dr2uOSVP0RoHy1C8lGNs9mNg2m1Ruq9909ti41HK3kgpGe0d0BbJVyx+EAIdC3Y05LToC9s/Ww3jGfwb4wISWCQubQSJcZFvZBJzPAqMHb44CQ==,iv:9ChJxUWZaK1S01Li63mxwiz6IeBLDLNc9Ex+dXVTZMY=,tag:p4hYNuO/INjPF8QQmrXYJw==,type:str]
sops:
    age:
        - recipient: age1t9hxk98xxze92rxjyq77q79gw7lf6jwa5pn83zqp037qq725z4lsxvqf8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTytQS1c3Q25PVGdwRzhx
            cjNmTVJkWVpVR243bW1Ybmk3M2l0UkNlRFV3ClBZc0VDUkdKR3VLTXpUQ0hzL1VL
            aU5McG0zeWJ3aFpudU1nVEs2OWd6Mk0KLS0tIE4rZHFmNGtCZDBDck8wWnpnclBE
            NVRHYnc2ZzF4b1FkdVhRMWVqRGlTUVUKB3qR0XnO+d6+W1mF0UQ5YLr1Na5/dQxd
            jP7vcObrWoqYgpjACXFYwaJSjiYIBj+HCl+KCRoPs/LL/w1aBUbPVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1da648as9sztwp6hkjlklqxzcynrxzqazywpw97x5rs7pmv7yup8sn08zqk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWGNCeVBFRlVzZ0w4bWJj
            N0cvaDBPQldQRW1kY2RuZ3N3cUNWWHR3OUUwClIvU3NoVVFQWEtBdnhQaEt5aFpj
            SG5DdU9VVXQxWlcyWWswR3k1bE12S2MKLS0tIDlGTWl0dWpUZmprNWF1S1Q1ajVa
            Z0JnRmlNVk1VNWhmam1nZGFkTk1wN0UKebdyW7LS4wmOo/ZA6xwy/z1ahvQYAsn3
            6ZzNZJM7dtkc377eTWWNbW57hxC3l7W/RKf1LY2Lzk+FOc4MU7Lmjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T15:01:27Z"
    mac: ENC[AES256_GCM,data:3jR9a8RDpIr+kISdWFg7WD1n+fUjtpxwglFQSs9DjZge5JtE5nt8mN/beCgMYyFQcm60nodslSOdQrhrF70zNE/SAr8VrmuWYraMCsPNE88R1KETTw2XqspleJSetR/nmhvfjgfPCfZH2+7cOtIOyXoitapsYctOaWU8DXI10ZE=,iv:epIn3wszHNEZKGKMHBUZsOSkZknp+VarAZySOc8aw5M=,tag:oI7imwzlLJl5AjYeSmKjSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
