apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: data-platform
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/nhientruong04/just-a-data-platform.git
  ref:
    branch: main
  secretRef:
    name: data-platform-auth
