apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: data-infra-apicurio
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: data-platform
  path: ./clusters/local/data-infra/schema-registry/apicurio
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: data-infra-registry-postgres-secret
