apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 30m
  releaseName: minio
  targetNamespace: data-infra
  chart:
    spec:
      chart: ./helm/storage/minio
      sourceRef:
        kind: GitRepository
        name: data-platform
        namespace: flux-system
      interval: 12h
