apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.startup.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  parallelism: 1
  template:
    spec:
      containers:
      - name: minio-startup
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command:
        - "/bin/bash"
        - "-c"
        - |
          {{- .Values.startup.script | nindent 10 }}
        restartPolicy: Never
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.auth.secret.name }}
              key: {{ .Values.auth.secret.userKey }}
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.auth.secret.name }}
              key: {{ .Values.auth.secret.passwordKey }}
      restartPolicy: Never
