apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: data-infra-kafka-connectors
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: data-platform
  path: ./clusters/local/data-infra/kafka/connectors
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: data-infra-kafka-connect
  - name: data-infra-platform-secrets
  - name: data-infra-prod-postgres-secret
  - name: data-prod-fake-prod-database
  - name: data-infra-minio
  - name: data-infra-apicurio
