apiVersion: v1
kind: Secret
metadata:
    name: prod-postgres-secret
type: Opaque
stringData:
    postgres_password: ENC[AES256_GCM,data:sR+3MRKSG9s=,iv:wyCEpeIxzpJW4vMUXxX2AGKbFjgknt62+or2gSBeRj4=,tag:gs2eCTGkUdgIv/sDVU+SOw==,type:str]
sops:
    age:
        - recipient: age1t9hxk98xxze92rxjyq77q79gw7lf6jwa5pn83zqp037qq725z4lsxvqf8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcVBGa2tjQzhDRTZLNU1T
            SnFWMGIzYmNhRTBYRXJxZHFDVlVpRkl4KzJzCnlTbzhEV3FWbUpxSzk0SldUSEZQ
            QXdnVFAzOGY2dGFhSjYzY3BDMExSMzQKLS0tIGtOdmpDTTBHclpYelRqcVZEWFox
            RzJOcG0rNjcvSU13SUlxZ3FkOXU5WVEK2SZM/wIK8v3uDoWbwYuFZQLeSFI//gV0
            tCV+JIwRzWlGLKpF2dO09vvqAZPGunvawDl9NMp3WdgOc0vbnJrqWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T06:38:07Z"
    mac: ENC[AES256_GCM,data:AP9C2Z82dtEErED3qpatW13ZfJShbdwieFofnww4NtT+ZuWP7cbo1om2kfUQD7xZGAg/PGhLdg5x/Qi7WW6DVT3e+FFe32VxhIZrXXuflG30C0g+/OzoQUU4PhEKtiexAiI/a3mUPUxPWTrxMaqWRbAZttkLlC1kPAwHhL71w48=,iv:zGEVI9BDFZT01zkl0/+uvij+W4kPzqygwty3h+twNT4=,tag:DzOd1NZmWrzhwq3cUn+bNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
