apiVersion: v1
kind: Secret
metadata:
    name: prod-postgres-secret
type: Opaque
stringData:
    postgres_password: ENC[AES256_GCM,data:sR+3MRKSG9s=,iv:wyCEpeIxzpJW4vMUXxX2AGKbFjgknt62+or2gSBeRj4=,tag:gs2eCTGkUdgIv/sDVU+SOw==,type:str]
sops:
    age:
        - recipient: age1t9hxk98xxze92rxjyq77q79gw7lf6jwa5pn83zqp037qq725z4lsxvqf8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWFd5QmZkZG9MeUttM04z
            S0JlRWpJZ244eXVkZ0dOcDZMV1hTU3BlcGtBCmd3YklESlBsSTNRZXhTWG9YRUlr
            Sjk0TUJZNEhZY0YxanlQYWc2d2N1WmsKLS0tIEU0UnQ0VUdsc2h1NUtBL3ZOTUQ4
            R2VQS2tVZ2ZXdG5tRWtwM2RFRENKV28KfhSeQO6pr5XmURdY6B/6YyG0RUtR+uRD
            +hjNaOBv+0Tnop6qKYG4tNLUsgxPc6j5Y1gkY+bjdd6s8r3kLzXzDw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1da648as9sztwp6hkjlklqxzcynrxzqazywpw97x5rs7pmv7yup8sn08zqk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RGpnZmh2dmxYSWYrWjl4
            V1ViNnVpdTVIN1R0dlZoNnU3TlRQT0RMT3hnCm9Sd2FGaXpQWmZnV2prN29pVUNO
            bG1McnRudXRWLzlENXVybGNERit5MEEKLS0tIFFYUWgxNmVPNHFsaC8rSjlQalcr
            VWZTUnpsZnhkcmdMbmVmcGZ5SkNLTWMKSTthGNLBAJNzBQyTDeRRZqmMCDwoKFal
            GmQiC2qXLTa+RWFrtB1qrFFPeB/fUnU3owBL7qZrGYScNcrLZgJiHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T06:38:07Z"
    mac: ENC[AES256_GCM,data:AP9C2Z82dtEErED3qpatW13ZfJShbdwieFofnww4NtT+ZuWP7cbo1om2kfUQD7xZGAg/PGhLdg5x/Qi7WW6DVT3e+FFe32VxhIZrXXuflG30C0g+/OzoQUU4PhEKtiexAiI/a3mUPUxPWTrxMaqWRbAZttkLlC1kPAwHhL71w48=,iv:zGEVI9BDFZT01zkl0/+uvij+W4kPzqygwty3h+twNT4=,tag:DzOd1NZmWrzhwq3cUn+bNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
