image:
  tag: "480"
  pullPolicy: IfNotPresent

# TODO: configure oauth2 authentication
server:
  workers: 0
  config:
    query:
      maxMemory: 6GB

env:
- name: MINIO_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: minio-secrets
      key: minio_user
- name: MINIO_SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: minio-secrets
      key: minio_password

catalogs:
  objectstore: |
    connector.name=iceberg
    iceberg.catalog.type=nessie
    iceberg.nessie-catalog.uri=https://dp-nessie-endpoint:19120/api/v2
    iceberg.nessie-catalog.ref=main
    iceberg.nessie-catalog.read-timeout=10s
    iceberg.nessie-catalog.default-warehouse-dir=s3://datalake-silver-zone/iceberg/default
    fs.native-s3.enabled=true
    s3.endpoint=http://dp-minio-endpoint:9000
    s3.region=us-east-1
    s3.path-style-access=true
    s3.aws-access-key=${ENV:MINIO_ACCESS_KEY}
    s3.aws-secret-key=${ENV:MINIO_SECRET_KEY}

coordinator:
  config:
    nodeScheduler:
      includeCoordinator: true

  resources:
    requests:
      cpu: 500m
      memory: 4Gi

  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 8
    failureThreshold: 3
    successThreshold: 1
