apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-secret
    namespace: data-infra
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:ZvyMlpKJPAi8dK1eW0Pfw7tUXQV1vYVWUvo0OcIDrE4+gRWm/bsf2Hl4wJQnmsuZxlAmFUcF5bMTeDfgPRLwboboQGQyJr5tzy+NTRJaUcb0dr2uOSVP0RoHy1C8lGNs9mNg2m1Ruq9909ti41HK3kgpGe0d0BbJVyx+EAIdC3Y05LToC9s/Ww3jGfwb4wISWCQubQSJcZFvZBJzPAqMHb44CQ==,iv:9ChJxUWZaK1S01Li63mxwiz6IeBLDLNc9Ex+dXVTZMY=,tag:p4hYNuO/INjPF8QQmrXYJw==,type:str]
sops:
    age:
        - recipient: age1t9hxk98xxze92rxjyq77q79gw7lf6jwa5pn83zqp037qq725z4lsxvqf8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGN2FEeXMzdWRLWVFQSXBz
            ZS9LNElRSXg3cWIrbXJUNkNuQmp4dWNQYmhrCnUxMjRDNlBoK3pOSHpmT0JpZURE
            bnAzSVNTTmlUcmJnVEljNDgrTnU3a3cKLS0tIEFKeXNYeVVhOVlYSWxtOTRrSzFa
            Q0Z0Z3BreVJCekxxcE1NK1NHV3NTbjQKYLn8UrRTCgvnB/IpI+/LkGEBTR9VfXu1
            Sx9U1IeUOvuQpEOdhjHWbQqaySICpx9K/oyHo4AS5a5+1Lkv2EJssg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T15:01:27Z"
    mac: ENC[AES256_GCM,data:3jR9a8RDpIr+kISdWFg7WD1n+fUjtpxwglFQSs9DjZge5JtE5nt8mN/beCgMYyFQcm60nodslSOdQrhrF70zNE/SAr8VrmuWYraMCsPNE88R1KETTw2XqspleJSetR/nmhvfjgfPCfZH2+7cOtIOyXoitapsYctOaWU8DXI10ZE=,iv:epIn3wszHNEZKGKMHBUZsOSkZknp+VarAZySOc8aw5M=,tag:oI7imwzlLJl5AjYeSmKjSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
