apiVersion: v1
kind: Secret
metadata:
    name: metastore-secrets
    namespace: data-infra
type: Opaque
data:
    postgres_password: ENC[AES256_GCM,data:pt7tv39t0+l6yOlU,iv:IhVJq3kRonJeH1xij8KBzSGQABQwqT4c82BCH/eTouM=,tag:vWvyjFgOQ+3ePGtt6MHvFw==,type:str]
sops:
    age:
        - recipient: age1t9hxk98xxze92rxjyq77q79gw7lf6jwa5pn83zqp037qq725z4lsxvqf8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cHduSlRkMVErZVRqWVRU
            TWxMVjJsWXYwNDNDcW5BRXJOT1VtcHp1alF3ClFwOHJYckFYajltVFoxcmRrTVZS
            NkYxUXJjNlRnaUpFOGtUbk1LN3psVkEKLS0tIGloNnREempxU201YWZtT2hpVzJl
            SGhhNDdrNW1sSnI3MnkrNStucTVMKzgKrGjDETV2QBD1FFhIP2HlMCqjxeSa50gr
            kyzQa7Z5yZ8wR4mOGjjiTb5MDtKns5VQ39KOySVjQrjDcmZu7BL96w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T14:10:02Z"
    mac: ENC[AES256_GCM,data:T2J1hYoJDiZbNqWyzpg8F/6tC7CMV9XwOUy9Jdf9DyYYJzqy2o/zb9PUj9AbAPTDbYB+M7yn0RD/ZMjkHJESmdWXvtt/OnTToksQo/wSI4hGeKFEjHfi/YvThbRw/1a7EREjJTT3AZrciUSgX9eHUFo3gAzqJNB08KlpTBGLhiA=,iv:l8CXD+lBYihDB6oDBauTIoylKkQXXE71VFkPDZUyFjk=,tag:jGnZNUNuS1F946SbmE1IyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
