apiVersion: v1
kind: Secret
metadata:
    name: minio-secrets
    namespace: data-infra
type: Opaque
data:
    minio_user: ENC[AES256_GCM,data:otMM5fdNMRUFUsN1JlIOkg==,iv:r6+sEvr1u9g5eJnTgPmSGz8/Ylj1pvhe9EMawDvmgiA=,tag:/0/XWkYn2SWlhs49K+Ayfg==,type:str]
    minio_password: ENC[AES256_GCM,data:+h/ug1EaVlkVKkOCk/fzZQ==,iv:LvtICc87HMl9TElH4hwuD/7ZPl9N2c1udP7MqzWJCA0=,tag:J+sPWVDErxAW5cCwrNSeZg==,type:str]
sops:
    age:
        - recipient: age1t9hxk98xxze92rxjyq77q79gw7lf6jwa5pn83zqp037qq725z4lsxvqf8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Tm54b2ZKR29WYWpHL2dU
            aGRtMXdFWThvQTRKOWZINHk2REd3Q3l1L0hvCmJlem84WEN5TURmaXNOYmJweXAr
            L1NtWVNzNlVzdWk2bVRJU1F3SE1HR1UKLS0tIHVNbGJVVDBPVEFCUnJSdjVOd25Z
            cUM1UzE3V09hV1A3SjV6cm5BRXRkdDgKCw2q9k61WiJ4jda9qvadiNdBCAsXiexe
            5Ys5PtT/WqxvT3jNJrotGOdyTKoNb4Ru3zrxe5VzUUE1IpOQNiHSvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T23:01:58Z"
    mac: ENC[AES256_GCM,data:tK2yOPj+lbN8zoM8Bp79DAScoR3SmWidRcEkwnfggcoqUklb9CfivGaefkNXU+NPMTBeH19YFFy+Ldc7S0JUO13EmIQe4Mi2S+aSqfhs4LPtMgY4HFC0LWpkAyM0q9qUv+BMkOWaeH1sVI5ST4svGe4bvSJ9808QOmGi+ootYK4=,iv:rYY073OF4B2Gfs8XT84yZpYb0AE871IkwI0MXdfTrFc=,tag:P75kRdAysLYfev/U/ow6DQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
