apiVersion: v1
kind: Secret
metadata:
    name: prod-postgres-secret
    namespace: data-prod
type: Opaque
stringData:
    postgres_password: ENC[AES256_GCM,data:VtaNS/vZ1YU=,iv:+6MhiKUq56n3Z9WkvxzovjeJwh066b2FCP51FF2xHI0=,tag:tr62ZOK5QcU6vlhVlQ/zFg==,type:str]
sops:
    age:
        - recipient: age1t9hxk98xxze92rxjyq77q79gw7lf6jwa5pn83zqp037qq725z4lsxvqf8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmelozRVVIMkdjOFJ3OEp5
            TnlXT2NOaTU2SHJGMTNqeHhocWk1SVYwYlFBCi9iblNYaFdTVXRzMm5YcWJzMndX
            cmFMaFpLM2h6YU84c2tyNmx6azg4QW8KLS0tIEdKYjdCRDBTR1BuQUF4V2ZCTkt6
            Y0lPZVlheGoxblc2M0FjMlNpbjJPR3MKMAOpw3kRBhQhvEjmHiE9KPXdQ5uQ0nfq
            NpAzRTq4MJzF+BO6wdkpNMrduykjN0KcA2tcIcHe8HdDznK47aBKTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T17:17:16Z"
    mac: ENC[AES256_GCM,data:Ihe8BL6TQw4ck0fiB9eCublNsRTNzdAT8ezUoEk6IcR5h+Q7ETzmMcQSWoZsFUg9mHzbiSB6p4e4KRtqH1j+BvwjYEHKv7G1TlCOovmSYmibRMvqry1Qu8TvfzLJvD+A/h+AD+qWbd7srdfC6dTyFDa82mXwuf8gsovntFo7GlI=,iv:GemSDPnX46p0WyB3Qd/60djRRwpTvYH4HSTgrQp7PKY=,tag:QMq5AkmgFt6VQoeewLLJtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
