apiVersion: v1
kind: Secret
metadata:
    name: infra-secrets
    namespace: data-infra
type: Opaque
data:
    minio_user: ENC[AES256_GCM,data:383OGs7ubbH+XT3glC0TMQ==,iv:LRpekQlVCMjjuTAo59QNO2/4hJrg4PZlbg2ThpkSlLg=,tag:HiOp4v3V6/yi3g15h8dgsg==,type:str]
    minio_password: ENC[AES256_GCM,data:EPUsa6g70CE2a0dCoVl5DA==,iv:40ysQS9ZXBMVHs+2DkUeQS+qZt7WWBn3gMAgI4h5mbI=,tag:4MVu1f3xb2DamED0nOcHMA==,type:str]
sops:
    age:
        - recipient: age1t9hxk98xxze92rxjyq77q79gw7lf6jwa5pn83zqp037qq725z4lsxvqf8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUDgzY0VySldYOXFuV25m
            Ry9OUWZVUFdYMHZHZmtFajAzb2o5UkVIZGtrClN2M1VnenVKV1h0YlFoY1lVZDJa
            R3BRSVhzYmRtbis3eTFZWlp3eS9Dd00KLS0tICtjSFhTQ0ZKUGQ4RThSUU1zdzJF
            cHlqbHVZR1A4SDI5NzZQQ3ZGYnVLenMK7PpCZERcT+uL58tTC8gmG4n0DGFLSW+G
            0HCTmOOXCud38lX53tqwnRGWsLwkTNfxFr9QZgeV/kDjUSl68WrP5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T21:22:12Z"
    mac: ENC[AES256_GCM,data:9mNRLx6qqXn/THhdqkW5ZFjygDg99F3stOF5f9t3Ou12tkcvO61KRx8I8Hf9Ema8RWXCdEla5TvHUUey2iov4puPbStvB0PqrAXgOONVPdL2XcY/tIKtTHyFfxk520LbZzBQq4DC5z780YwwtqneHnGHyRSgPKppjthgBbfSPks=,iv:OVxSPlcrEiVZBoUH9ZBCLvjhYFfQcIIqOobPyda3XB0=,tag:dzaX3Zvk0s+634vlCeyoxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
