apiVersion: v1
kind: Secret
metadata:
    name: metastore-secrets
    namespace: data-infra
type: Opaque
data:
    postgres_password: ENC[AES256_GCM,data:pt7tv39t0+l6yOlU,iv:IhVJq3kRonJeH1xij8KBzSGQABQwqT4c82BCH/eTouM=,tag:vWvyjFgOQ+3ePGtt6MHvFw==,type:str]
sops:
    age:
        - recipient: age1t9hxk98xxze92rxjyq77q79gw7lf6jwa5pn83zqp037qq725z4lsxvqf8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQ21qeVRqWURCbHhDc04w
            dWJWRjNnZnVWd0ljSEVpeWgxSUwweWo1bGlNCi85TWRqWk9xYk9BRUcybGpoZUpP
            THdRRVROYytvVmF1Z1NHMWxWZ2tHTnMKLS0tIDkrbk5DdFNNVkdSenpDV3dEVjdu
            VTlVcis1NlMydlo3ZVcvZ3ltaVhZazQK57pAFyJLq3M55eJmrIIkqk6dgu3SvZ2U
            tuJraIui9+rK7boXnD1B538og3MUb1s868scfOAvt9Zf4mf7mnZY2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1da648as9sztwp6hkjlklqxzcynrxzqazywpw97x5rs7pmv7yup8sn08zqk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWldxY0llKytVSW5nVXB2
            bmtYemNHajZwZThWeVljZWJncW1BQzJDY2k4ClRMU2ZIRm5PNmdjSGFFREhMSlRx
            RTZEcHp2UmR5N29sT00wMWlXV1FlRkkKLS0tIDJQTC81OTlrd1pVUHFSdmFVd1Jt
            L2hKRjZVSDB1M3BnTDZ6K3QvLzkxdTgKVniG0ibBjBMX8zlj7k7aqxb3Gx8fsdpA
            jp0IviSKvDb8GdGrrU06a8xHXDX29c5i63tBfUTkDVcyivMhxL4idw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T14:10:02Z"
    mac: ENC[AES256_GCM,data:T2J1hYoJDiZbNqWyzpg8F/6tC7CMV9XwOUy9Jdf9DyYYJzqy2o/zb9PUj9AbAPTDbYB+M7yn0RD/ZMjkHJESmdWXvtt/OnTToksQo/wSI4hGeKFEjHfi/YvThbRw/1a7EREjJTT3AZrciUSgX9eHUFo3gAzqJNB08KlpTBGLhiA=,iv:l8CXD+lBYihDB6oDBauTIoylKkQXXE71VFkPDZUyFjk=,tag:jGnZNUNuS1F946SbmE1IyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
