apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres-kafka-connect.yaml
- minio-kafka-connect.yaml
- role/prod-postgres/role.yaml
- role/prod-postgres/role-binding.yaml
