apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: postgres-kafka-connect-cluster
  namespace: data-infra
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 4.2.0
  replicas: 1
  bootstrapServers: kafka-kafka-bootstrap:9093
  groupId: kafka-connect-group
  configStorageTopic: prod-postgres-dbz-connect-configs
  statusStorageTopic: prod-postgres-dbz-connect-status
  offsetStorageTopic: prod-postgres-dbz-connect-offsets
  resources:
    requests:
      cpu: 200m
      memory: 1.5Gi
    limits:
      cpu: 500m
      memory: 2Gi
  tls:
    trustedCertificates:
      - secretName: kafka-cluster-ca-cert
        pattern: "*.crt"
  config:
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    key.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: http://dp-apicurio-registry-endpoint.data-infra.svc.cluster.local:8081/apis/ccompat/v7
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://dp-apicurio-registry-endpoint.data-infra.svc.cluster.local:8081/apis/ccompat/v7
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  build:
    output:
      type: docker
      image: docker.io/nhientruong/data-platform:debezium-postgresql-connector-3.5.0
      pushSecret: dockerhub-secret
    plugins:
    - name: debezium-postgresql-connector
      artifacts:
      - type: tgz
        url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/3.5.0.Final/debezium-connector-postgres-3.5.0.Final-plugin.tar.gz
    - name: kafka-connect-avro-converter
      artifacts:
      - type: maven
        repository: https://packages.confluent.io/maven/
        group: io.confluent
        artifact: kafka-connect-avro-converter
        version: 8.2.0
  template:
    buildContainer:
      securityContext:
        privileged: true
