apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sources
- namespaces
- data-prod/secrets
- data-prod/database
- data-infra/secrets
- data-infra/storage
- data-infra/metastore
- data-infra/schema-registry
- data-infra/kafka
- data-infra/ui
