apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "prod-postgres-database.postgresName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "prod-postgres-database.labels" . | nindent 4 }}
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  serviceName: postgres
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: database
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.postgres.port }}
          name: postgres
        args:
          {{- toYaml .Values.postgres.args | nindent 10}}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.auth.username | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgres.auth.passwordSecret.name }}
              key: {{ .Values.postgres.auth.passwordSecret.key }}
        resources:
          {{- toYaml .Values.postgres.resources | nindent 10 }}
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "{{ .Values.postgres.auth.username }}"]
          periodSeconds: {{ .Values.postgres.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.postgres.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.postgres.livenessProbe.failureThreshold }}
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "{{ .Values.postgres.auth.username }}"]
          periodSeconds: {{ .Values.postgres.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.postgres.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.postgres.readinessProbe.failureThreshold }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: schema
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: schema
        configMap:
          name: postgres-schema
  volumeClaimTemplates:
  - metadata:
      name: data
      namespace: {{ .Values.namespace.name }}
      labels:
        {{- include "prod-postgres-database.labels" . | nindent 8 }}
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: database
    spec:
      accessModes:
      - {{ .Values.postgres.persistence.accessMode }}
      {{- if .Values.postgres.persistence.storageClassName }}
      storageClassName: {{ .Values.postgres.persistence.storageClassName | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.postgres.persistence.size }}
