apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "prod-postgres-database.labels" . | nindent 4 }}
    app.kubernetes.io/name: postgres
spec:
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
  ports:
  - name: postgres
    protocol: TCP
    port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}
