apiVersion: v1
kind: Secret
metadata:
    name: minio-secrets
    namespace: data-infra
type: Opaque
data:
    minio_user: ENC[AES256_GCM,data:otMM5fdNMRUFUsN1JlIOkg==,iv:r6+sEvr1u9g5eJnTgPmSGz8/Ylj1pvhe9EMawDvmgiA=,tag:/0/XWkYn2SWlhs49K+Ayfg==,type:str]
    minio_password: ENC[AES256_GCM,data:+h/ug1EaVlkVKkOCk/fzZQ==,iv:LvtICc87HMl9TElH4hwuD/7ZPl9N2c1udP7MqzWJCA0=,tag:J+sPWVDErxAW5cCwrNSeZg==,type:str]
sops:
    age:
        - recipient: age1t9hxk98xxze92rxjyq77q79gw7lf6jwa5pn83zqp037qq725z4lsxvqf8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWVZRc1hobXF6VURRTUJH
            QVROeDNLQnJoSEpIT1JaVlRoVWRpaTFZaEhNClAyK0F0ZGVtejVZald6dFgxa1RM
            Vy9xenZGTDBGVjV6eHZIQzdOWDlKRG8KLS0tIFhEOVIvNDUwMW82YnBBNkdOdVIx
            d3JQRDJ4bjdnanlqRm9hZjY0bS9CZFEKltX03RzvPy4HjbMwnPrJ1g9uzIEVBRfv
            +gfBnWcavlBOR221Wd/FJscaAOvdhfmeGtQq9X1F1KrUvJ8tw20eAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1da648as9sztwp6hkjlklqxzcynrxzqazywpw97x5rs7pmv7yup8sn08zqk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONllvejREWUtudjFiS0or
            UjJkZFBFWlZoOTNDUkMrY1hURFoxMFZCd0hZCkxVUWpHMC9VQ3N3RXdkYWNycU4x
            aGJnVXlTUU9UTGtiempOdEJ1VzVoTzgKLS0tIGZmbnNJN1BqUjRaajNyNVpTSWFX
            TkZzTnNMM3N2QVdWeU1wK1ZpUEJrOVkKt0y0CEtlWicnAa26rj+mcyXhMW7u/cb4
            PgsbYPgSIV1tpaKh/gO6sW99w66wP9PGGpkd2NeoRC8H3QQEdwXB/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T23:01:58Z"
    mac: ENC[AES256_GCM,data:tK2yOPj+lbN8zoM8Bp79DAScoR3SmWidRcEkwnfggcoqUklb9CfivGaefkNXU+NPMTBeH19YFFy+Ldc7S0JUO13EmIQe4Mi2S+aSqfhs4LPtMgY4HFC0LWpkAyM0q9qUv+BMkOWaeH1sVI5ST4svGe4bvSJ9808QOmGi+ootYK4=,iv:rYY073OF4B2Gfs8XT84yZpYb0AE871IkwI0MXdfTrFc=,tag:P75kRdAysLYfev/U/ow6DQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
