apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-nessie
  namespace: data-infra
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nessie
      app.kubernetes.io/component: metastore
      app.kubernetes.io/instance: dp
  replicas: 1
  # TODO: rolling updates
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nessie
        app.kubernetes.io/component: metastore
        app.kubernetes.io/instance: dp
    spec:
      initContainers:
      - name: minio-check
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |
          until wget -qO- http://dp-minio-endpoint:9000/minio/health/ready; do
            echo 'Waiting for MinIO...'
            sleep 2
          done

      containers:
      - name: nessie
        image: ghcr.io/projectnessie/nessie:0.107.4
        resources:
          requests:
            cpu: 400m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 2000Mi
        livenessProbe:
          httpGet:
            path: /q/health
            port: 9000
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 15
        readinessProbe:
          httpGet:
            path: /q/health
            port: 9000
          periodSeconds: 5
          timeoutSeconds: 2
        env:
        - name: QUARKUS_DATASOURCE_POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: metastore-secrets
              key: postgres_password
        - name: NESSIE_CATALOG_SECRETS_ACCESS_KEY_NAME
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: minio_user
        - name: NESSIE_CATALOG_SECRETS_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: minio_password
        volumeMounts:
        - name: nessie-config
          mountPath: /deployments/config

      volumes:
      - name: nessie-config
        configMap:
          name: nessie-config
