apiVersion: v1
kind: Service
metadata:
  name: dp-nessie-endpoint
  namespace: data-infra
spec:
  selector:
    app.kubernetes.io/name: nessie
    app.kubernetes.io/component: metastore
    app.kubernetes.io/instance: dp
  ports:
  - name: nessie-portal
    protocol: TCP
    port: 9000
    targetPort: 9000
  - name: nessie-api
    protocol: TCP
    port: 19120
    targetPort: 19120
