apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nessie
  namespace: flux-system
spec:
  interval: 30m
  releaseName: nessie
  targetNamespace: data-infra
  chart:
    spec:
      chart: ./helm/metastore/nessie
      sourceRef:
        kind: GitRepository
        name: data-platform
        namespace: flux-system
      interval: 12h
